name: Discord Push

on:
  release:
    types: [published]

jobs:
  sending:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      uses: LeGitHubDeTai/github-to-discord@main
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: Test
        MESSAGE_COLOR: 5814783
        CONTENT: null
        MESSAGE_TITLE: "New Version"
        SECTION_NAME: "ChangeLog"
        IMAGE: null;
